services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  seed:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce

volumes:
  mongo-data:
